# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Dojo
subtitle:
description:
author: SitePen
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://dojo.github.io
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: ../_dist
tag_dir: tags
archive_dir: blog
category_dir: categories
code_dir: tutorials
i18n_dir: :lang
skip_render:
  - "**/*/demo"
tutorial_dir: tutorials

# Writing
new_post_name: :year/:month/:day-:title/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: true
  tab_replace:

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'default'
  line_number: false    # default false

# Authors
authors:
  default:
    name: The Dojo Team
  dylan:
    name: Dylan Schiemann
    email: dylan@sitepen.com

yasr:
  axis: true              # Enables Axis (Recommends Nib) 
  compress: false         # Disables Compression 
  jeet: true              # Enables Jeet 
  nib: true               # Enables Nib 
  rupture: true           # Enables Rupture 
  typographic: false       # Enables Typographic 


# Category & Tag
default_category: dojo
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM Do YYYY, h:mm:ss a
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# index-generator-3
## Docs https://github.com/carlhopf/hexo-generator-index3
# index_generator:
#  tutorials:
#    per_page: 4
#    order_by: -date
#    include:
#      - tag tutorials
#    layout: 
#      - archive

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: dojo

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

